// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL6_8rXKJqNVfZfF0qVmS7VOJ7BsjPe98',
    appId: '1:65133375738:web:e3b217eba3e2506bfa5943',
    messagingSenderId: '65133375738',
    projectId: 'ecommerce-5a66f',
    authDomain: 'ecommerce-5a66f.firebaseapp.com',
    storageBucket: 'ecommerce-5a66f.appspot.com',
    measurementId: 'G-8ZLFMQYXSH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm7bkVdx8Hte1k0iZU_DuVXfdsSbpR9yg',
    appId: '1:65133375738:android:fdb6fddc631a6adafa5943',
    messagingSenderId: '65133375738',
    projectId: 'ecommerce-5a66f',
    storageBucket: 'ecommerce-5a66f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrP_Pdl3O0fQjz1zxfkgpxf88KiO3PHZ8',
    appId: '1:65133375738:ios:28f87a21bc8ee7c2fa5943',
    messagingSenderId: '65133375738',
    projectId: 'ecommerce-5a66f',
    storageBucket: 'ecommerce-5a66f.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrP_Pdl3O0fQjz1zxfkgpxf88KiO3PHZ8',
    appId: '1:65133375738:ios:28f87a21bc8ee7c2fa5943',
    messagingSenderId: '65133375738',
    projectId: 'ecommerce-5a66f',
    storageBucket: 'ecommerce-5a66f.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBL6_8rXKJqNVfZfF0qVmS7VOJ7BsjPe98',
    appId: '1:65133375738:web:cf3dfdf209a33cdbfa5943',
    messagingSenderId: '65133375738',
    projectId: 'ecommerce-5a66f',
    authDomain: 'ecommerce-5a66f.firebaseapp.com',
    storageBucket: 'ecommerce-5a66f.appspot.com',
    measurementId: 'G-QMR9MCEJXV',
  );
}
